spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/exchanger
    username: root
    password: password
    driver-class-name: org.postgresql.Driver
